[build]
publish = "public"
#command = "hugo --gc"

[context.production]
#HUGO_VERSION = "v0.80.0"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
#HUGO_VERSION = "v0.80.0"
HUGO_ENV = "production"


#[context.deploy-preview.environment]
#HUGO_VERSION = "0.80.0"
#HUGO_ENV = "deploy-preview"
#HUGO_ENABLEGITINFO = "true"
#
#[context.branch-deploy.environment]
#HUGO_VERSION = "0.80.0"
#HUGO_ENV = "deploy-preview"
#HUGO_ENABLEGITINFO = "true"