backend:
  name: git-gateway
#  repo: aspose-html-cloud/aspose-html-cloud-docs
  branch: develop_apiv4
  squash_merges: true

# when using the default proxy server port
#local_backend: true

local_backend:
  # when using a custom proxy server port
  url: http://localhost:8082/api/v1
  # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
  allowed_hosts: ['192.168.0.1']
#  use_graphql: true

#site_url: https://aspose-html-cloud-docs.netlify.app
display_url: https://docs.aspose.cloud/
media_folder: static/images
public_folder: /images
publish_mode: editorial_workflow
enableIdentityWidget: false
show_preview_links: true
slug:
  clean_accents: false

collections:
  - name: html
    label: HTML
    label_singular: "Page"
    folder: content/html
    create: true
    media_folder: ''
    public_folder: ''
    preview_path: "html/{{slug}}"
#    preview_path: "html/{{dirname}}/{{filename}}.html"
    nested:
      depth: 100
      summary: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Keywords", name: "keywords", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Weight", name: "weight", widget: "number", value_type: "int", default: 10, step: 10, min: 1, max: 1000, required: false }
#      - {label: "Type", name: "type", widget: "select", default: "docs", options: ["docs"], allow_add: false, required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "docs"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
    meta: { path: { widget: string, label: "Path", index_file: "_index" } }
    summary: "[{{weight}}] - {{title}}"
#    summary: "{{commit_date}} {{commit_author}} [{{weight}}]  : {{title}} "
